import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu";
import News from "./components/News";
import Footer from "./components/Footer";
import Cotizador from "./components/Cotizador";
import Isapres from "./components/Isapres";
import CotizacionOnline from "./components/CotizacionOnline";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <div
          style={{
            backgroundImage: "url('/images/bg-cotizador.jpeg')",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          <Menu />
          <Cotizador />
        </div>

        <Isapres />

        <CotizacionOnline />
        <News />

        <Footer />
      </body>
    </html>
  );
}
